-- ============================================================================
-- LAYER 2: what an auditor reads. One row per business action.
-- ============================================================================
CREATE TABLE audit_events (
  id            bigserial,
  occurred_at   timestamptz NOT NULL DEFAULT clock_timestamp(),
  request_id    uuid        NOT NULL,   -- UUIDv7, generated by the application
  action        text        NOT NULL,   -- "order.submitted"
  actor_type    text,                   -- User | ApiKey | NULL for system
  actor_id      bigint,
  actor_label   text,                   -- "Jane Smith <jane@x.com>"   SNAPSHOT
  subject_type  text,
  subject_id    bigint,                 -- the aggregate root
  -- The request_id of the EARLIER unit of work that caused this one to exist:
  -- the request that enqueued this job. Distinct from request_id, which
  -- identifies THIS unit of work; the two are never equal on the same row. A job
  -- deliberately does not inherit its enqueuer's request_id (see the note in
  -- job_context.rb), so this column is what keeps the causal chain queryable.
  -- A real column rather than a metadata key: it is queried in both directions,
  -- it is exactly one uuid, and metadata belongs to the ACTION's payload -- a
  -- registered action carrying its own "caused_by_request_id" key would
  -- otherwise collide with the framework's.
  caused_by_request_id uuid,
  source        text        NOT NULL,   -- web | api | job | console | system
  ip            inet,
  user_agent    text,
  summary       text        NOT NULL,   -- rendered human sentence     SNAPSHOT
  metadata      jsonb       NOT NULL DEFAULT '{}',
  PRIMARY KEY (id, occurred_at)         -- PG requires the partition key in the PK
) PARTITION BY RANGE (occurred_at);

CREATE INDEX audit_events_occurred_at_idx  ON audit_events (occurred_at DESC);
CREATE INDEX audit_events_actor_idx        ON audit_events (actor_type, actor_id, occurred_at DESC);
CREATE INDEX audit_events_action_idx       ON audit_events (action, occurred_at DESC);
CREATE INDEX audit_events_subject_idx      ON audit_events (subject_type, subject_id, occurred_at DESC);
CREATE INDEX audit_events_request_id_idx   ON audit_events (request_id);

-- Partial: only job- and cascade-originated events carry a cause, so the index
-- covers a small minority of rows. occurred_at is included because the screen
-- orders by it and because a bounded drill-down can then be answered from the
-- index alone.
CREATE INDEX audit_events_caused_by_idx ON audit_events (caused_by_request_id, occurred_at DESC)
  WHERE caused_by_request_id IS NOT NULL;

-- ============================================================================
-- LAYER 1: forensic detail. One row per row-level change.
-- Written ONLY by public.audit_row_change().
-- ============================================================================
CREATE TABLE audit_changes (
  id              bigserial,
  occurred_at     timestamptz NOT NULL DEFAULT clock_timestamp(),
  request_id      uuid,                  -- NULL = out-of-band write; see §9
  record_type     text    NOT NULL,      -- "Order" (model name, not table name)
  record_id       bigint  NOT NULL,
  operation       char(1) NOT NULL,      -- I | U | D
  diff            jsonb   NOT NULL,      -- {"status": ["pending", "approved"]}
  changed_columns text[]  NOT NULL,      -- {status}  -- denormalized keys of diff
  actor_type      text,
  actor_id        bigint,
  actor_label     text,                  -- SNAPSHOT, same string layer 2 wrote
  PRIMARY KEY (id, occurred_at),
  CONSTRAINT audit_changes_operation_check CHECK (operation IN ('I', 'U', 'D'))
) PARTITION BY RANGE (occurred_at);

CREATE INDEX audit_changes_actor_idx       ON audit_changes (actor_type, actor_id, occurred_at DESC);
CREATE INDEX audit_changes_record_idx      ON audit_changes (record_type, record_id, occurred_at DESC);
CREATE INDEX audit_changes_record_type_idx ON audit_changes (record_type, occurred_at DESC);
CREATE INDEX audit_changes_request_id_idx  ON audit_changes (request_id);
CREATE INDEX audit_changes_occurred_at_idx ON audit_changes (occurred_at DESC);

-- The ONLY GIN index on this table, and it is on text[] rather than on `diff`.
-- A jsonb_path_ops GIN index does not support the `?` key-existence operator at
-- all -- only @>, @? and @@ -- so "which changes touched status" would silently
-- fall back to a sequential scan. The default jsonb_ops opclass does support `?`
-- but indexes every key AND every value, making it far larger than needed here.
CREATE INDEX audit_changes_changed_columns_idx ON audit_changes USING gin (changed_columns);
